#!/usr/bin/env bash

FOCUSED_COLOR=$(get_xresource_color color4)
NORMAL_COLOR=$(get_xresource_color background)
ACTIVE_COLOR=$(get_xresource_color color8)
PRESEL_COLOR=$(get_xresource_color color1)

FLOATING_APPS=(
  Blueman-manager
  EpsonPrinterUtility
  Gimp
  mplayer2
  Nm-connection-editor
  pavucontrol
)

########### MONITORS  ##########
bspc monitor HDMI-A-0 -d 1 3 5 7 9
bspc monitor HDMI-A-1 -d 2 4 6 8

########### WINDOWS  ##########
bspc config border_width 3
bspc config window_gap 5
bspc config split_ratio 0.5
bspc config top_padding 30

########### GENERAL  ##########
bspc config single_monocle false
bspc config focus_follows_pointer false
bspc config borderless_monocle true
bspc config gapless_monocle true

########### COLORS  ##########
bspc config focused_border_color "$FOCUSED_COLOR"
bspc config normal_border_color "$NORMAL_COLOR"
bspc config active_border_color "$ACTIVE_COLOR"
bspc config presel_feedback_color "$PRESEL_COLOR"

########### RULES  ##########
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

for app in ${FLOATING_APPS[*]}; do
  bspc rule -a "$app" state=floating focus=on
done

########### AUTOSTARTS  ##########
pgrep -x sxhkd >/dev/null || sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &
dunst &
feh --bg-fill /home/maky/Pictures/wallpapers/TDM_08.png /home/maky/Pictures/wallpapers/Clearnight.jpg
/home/maky/PersonalHome/Scripts/MyApps/dimmer/dimmer_time_check.sh &
/home/maky/.config/bspwm/polybar/launch.sh &
picom --config ~/.config/picom.conf &

# set of commands to disable the screensaver
xset s off &
xset -dpms &
xset s noblank &
