#! /bin/sh

FOCUSED_COLOR=$(get_xresource_color color4)
NORMAL_COLOR=$(get_xresource_color background)
ACTIVE_COLOR=$(get_xresource_color color8)
PRESEL_COLOR=$(get_xresource_color color1)

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-A-0 -d 1 3 5 7 9
bspc monitor HDMI-A-1 -d 2 4 6 8

bspc config border_width 3
bspc config window_gap 5

bspc config split_ratio 0.5
bspc config single_monocle false
bspc config focus_follows_pointer false
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config top_padding 30

bspc config focused_border_color "$FOCUSED_COLOR"
bspc config normal_border_color "$NORMAL_COLOR"
bspc config active_border_color "$ACTIVE_COLOR"
bspc config presel_feedback_color "$PRESEL_COLOR"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

pgrep -x sxhkd >/dev/null || sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &
dunst &
feh --bg-fill /home/maky/Pictures/wallpapers/TDM_08.png /home/maky/Pictures/wallpapers/Clearnight.jpg
/home/maky/PersonalHome/Scripts/MyApps/dimmer/dimmer_time_check.sh &
/home/maky/.config/bspwm/polybar/launch.sh &
